#ifndef __APIC_H
#define __APIC_H

#define DEFAULT_IO_APIC_ADDRESS				0xFEC00000

#define LOCAL_APIC_ID_REGISTER				0x20
#define LOCAL_APIC_ID_VERSION_REGISTER		0x30
#define SPURIOUS_INTERRUPT_VECTOR_REGISTER	0xF0
#define ERROR_STATUS_REGISTER				0x280
#define INTERRUPT_COMMAND_REGISTER_1		0x300
#define INTERRUPT_COMMAND_REGISTER_2		0x310


#endif
